### ISSUE TITLE
Goodreads

### ISSUE THREAD

**Issue by morningscifi** [bitfield/tpg-tests#1]
I'd love to see The Power of Go Tests appear on Goodreads--I'm happy to submit a request to their Librarians Group, but I figured I'd ask here first if anyone could suggest an official publication date. Perhaps September 5th, 2022 because of [this commit](https://github.com/bitfield/tpg-tests/commit/1dd72b3128bd15db4c111000a632fb1344d37d2a)?

Thanks!

**Comment by bitfield** [comment]
Yes, that sounds about right!
